### ISSUE TITLE
Keyframes not working

### ISSUE THREAD

**Issue by tinaconrad** [armin-pfaeffle/sass-autocompile#130]
Hello! I found a problem with this plugin. Not sure if I'm doing something wrong, but I followed every step on this page to make animated sprites: 
http://blog.teamtreehouse.com/css-sprite-sheet-animations-steps
.monster {
  width: 190px;
  height: 240px;
  background: url('monster-sprite.png') left center;
  animation: play 0.8s;
}
@keyframes play {
   100% { background-position: -1900px; }
}
It was animating when I was using a different SASS compiler in another IDE, but when I used the sass-autocompile for atom, the animation went away. Is there anything I'm supposed to do to make this animation work? Thanks!

**Comment by IiroP** [comment]
Can you post your output css from sass-autocompiler (not working) and some else compiler (working)?

**Comment by tinaconrad** [comment]
If its working, there will be a CSS output like this one: 
 ```
animation: handshake_sprite 3s steps(82) infinite;
@keyframes handshake_sprite { 
	100% { background-position: -25584px; }
}
```
If its not working, nothing shows up.

**Comment by armin-pfaeffle** [comment]
Hey Tina!

When I compile this file
```scss
.monster {
	width: 190px;
	height: 240px;
	background: url('monster-sprite.png') left center;
	animation: play 0.8s;
}
@keyframes play {
	100% { background-position: -1900px; }
}
```
This is the output -- which exactly is that what should be the result:
```css
.monster {
    width: 190px;
    height: 240px;
    background: url("monster-sprite.png") left center;
    animation: play 0.8s;
}

@Keyframes play {
    100% {
        background-position: -1900px;
    }
}
```
Do you include other "libraries"?! Can you give me a simple example which demonstrates that bug?

Btw.: My package does not compile anything. It's only a wrapper for [node-sass](https://www.npmjs.com/package/node-sass)
