### ISSUE TITLE
Sass-autocompile not working with compass

### ISSUE THREAD

**Issue by ravisharmads** [armin-pfaeffle/sass-autocompile#150]
@sass-autocompile is not working with compass .
![error](https://user-images.githubusercontent.com/15167674/41158351-3f342c74-6b46-11e8-8b09-00bed3958483.png)

Atom - Error- File to import not found or unreadable: compass
Netbeans - Working fine

Please Help!

**Comment by armin-pfaeffle** [comment]
Hey!

I downloaded the stable ZIP file and tried to include Compass like this:
```SCSS
// compileCompressed: all.min.css, includePath: "D:\TEMP\compass-stable\compass-stable\core\stylesheets"

@import 'compass';

body {
	background-color: $grid-background-column-color;
}
````
... and it works!

You have to set the `includePath`parameter and then import compass. But perhaps there are some features used by compass that won't work with the SASS compiler [node-sass](https://github.com/sass/node-sass), my package is built on.

[Btw:](https://github.com/Compass/compass)
> Compass is no longer actively maintained.
