### ISSUE TITLE
Filter CSS property isn't brought to the compiled result

### ISSUE THREAD

**Issue by djmonzyk** [armin-pfaeffle/sass-autocompile#167]
I have a class with a filter css property.  I compile the file and the rest of the properties from the class are compiled, but the filter properties are nowhere in the rendered file's relevant class.
`filter: grayscale(1);`

**Comment by armin-pfaeffle** [comment]
Hey! With this example everything works totally fine:

```scss
// compileCompressed: $1.min.css

body {
	filter: grayscale(1);
}
```

Can you send me an example? But before, update your node-sass installation and retry!
