### ISSUE TITLE
@import Google Webfont problem.

### ISSUE THREAD

**Issue by felipefgoncalves** [armin-pfaeffle/sass-autocompile#89]
Hi! I got this compile error with my file. In line 23, there is an error mentioned by sass-autocompile, which don't let me compile and create my .css file. How can I proceed?

![screenshot 2016-09-04 20 35 38](https://cloud.githubusercontent.com/assets/21992328/18234609/99f5e9a4-72e1-11e6-8e14-43948bc22cdb.jpg)

**Comment by armin-pfaeffle** [comment]
Hey! The problem is not my packages. Your SCSS is wrong! Using quotes fixes that problem. And I also removed the brackets around `{$font}`.
```scss
@mixin google-font($font) {
	$font: unquote($font);
	@import url('https://fonts.googleapis.com/css?family=#{$font}');
}
```
